language: php

env:
  global:
    - XDEBUG_MODE=coverage

# Versions of PHP you want your project run with.
php:
  - 8.1
# Commands to be run before your environment runs.

before_script:
  - composer install --no-interaction
  - composer dump-autoload
  - cp .env.example .env

# Commands you want to run that will verify your build.

script:
  - phpunit --coverage-clover=coverage.xml

after_success: bash <(curl -s https://codecov.io/bash)

# allow_failures: Allow this build to fail under the specified environments.

# fast_finish: If your build fails do not continue trying to build, just stop.

matrix:
  allow_failures:
    - php: 8.1
  fast_finish: true
